### ISSUE TITLE
2019.11.23 멋쟁이사자처럼 컨퍼런스 추가

### ISSUE THREAD

**Issue by jebae** [innovationacademy-kr/community-meetups#27]
| 2019.11.23 | [멋쟁이 사자처럼 컨퍼런스: 세렝게티](http://class.likelion.net/lecture_detail/7/) | 서울</br>강남 | #스타트업 #네트워킹 #채용 #비전공자 | 유료 |

추가 부탁요.

**Comment by minsuklee** [comment]
추가 되었습니다
