### ISSUE TITLE
연사자 모집 코너 추가

### ISSUE THREAD

**Issue by samchon** [innovationacademy-kr/community-meetups#31]
현재 이 저장소에는 오로지 연사자가 모두 모집되고 개최가 확정된 모임만 기록되고 있습니다. 하지만, 밋업을 주최할 때 중요한 것 중에 하나가 바로 발표 주제를 정하고, 연사자를 모집하는 것입니다. 따라서 README 에 새로운 단원을 추가하거나, 혹은 새로운 md 문서를 만들어 연사자 모집 코너를 만들어보심이 어떠하신지요?

**Comment by minsuklee** [comment]
좋은 의견입니다. 12월 부터는 연사모집 링크를 추가할 수 있도록 하겠습니다.
