### ISSUE TITLE
설리번프로젝트 2020 겨울학기 설명회

### ISSUE THREAD

**Issue by sigridjineth** [innovationacademy-kr/community-meetups#32]
청소년 코딩교육 봉사단체 설리번프로젝트가 2020년 겨울학기 설명회를 개최합니다.
특성화고 학생들이 직접 또래와 호흡하는 비영리 무료교육이며, 어린이/청소년을 대상으로 합니다.

https://event-us.kr/sullivanproject/event/13622

**Comment by minsuklee** [comment]
등록되었습니다
