### ISSUE TITLE
AWS Summit Online Korea 등록

### ISSUE THREAD

**Issue by kwangsooshin** [innovationacademy-kr/community-meetups#41]
https://aws.amazon.com/ko/events/summits/online/korea/?sc_channel=em&sc_campaign=apac_field_t1_aws-summit-online-korea_20200513&sc_publisher=aws&sc_medium=em_&sc_content=event_ev_summit&sc_country=mult&sc_geo=mult&sc_category=mult&sc_outcome=event&trkCampaign=aws-online-summit&trk=em_summit_online_conf&mkt_tok=eyJpIjoiTm1RME1qazBOR00zT1RVNCIsInQiOiJTaWFTNHIrVTRMcktCa3RMQ0Z6YjAwYU8zbkNxUkx1YldaaEdUT0l4VitMakdKWTlqWUdDSzlnaldKbW9pdXFKeTlSMkNaeitRYVBnXC9ON25ycFdTWkFOZ2htK2JSWXR6VUp0ZXRCVFVTbk1oMVBhazFhaGhvN09zTjlQcWF6K2U3UnltbXlmZDZCMGZXT3Vpdzc5cndRPT0ifQ%3D%3D

**Comment by minsuklee** [comment]
등록했습니다. 고맙습니다.
