### ISSUE TITLE
"커뮤니티 행사"의 정의 관련 문의

### ISSUE THREAD

**Issue by combacsa** [innovationacademy-kr/community-meetups#5]
안녕하세요. 이 저장소에 리스트업 가능한 밋업에 대해 문의드립니다.

* 참가신청기간이 이미 끝났더라도 목록에 추가할 수 있는지?
* 참가신청자에 제한이 있거나 추첨을 통해 선발하더라도 목록에 추가할 수 있는지?

어떤 행사들이 리스트업할만한 행사이고, 이런 행사들은 리스팅에 지양했으면 한다 하는 기준에 대한 문서가 이를테면 Wiki 에 정리되면 좋을 거 같습니다.

고맙습니다.

**Comment by minsuklee** [comment]
참가 신청이 끝나도, 추첨을 해도 상관없습니다. 모든 목록을 만드는 것이 목표이고, 전년도 리스트를 보고 올해 어떤 일이 있을지 예측 할 수 있다는 것이 중요하죠..
리스트업 할만한 행사는 '개발자' 중심의 행사를 가정해서 비교적 잘 이해가 된다고 생각했는데, 약간 더 생각해보고 문구를 넣도록 하겠습니다.
의견 고맙습니다.
